### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by Moskovych** [armosec/homebrew-kubescape#3]
Release: https://github.com/armosec/kubescape/releases/download/v1.0.136/kubescape-macos-latest

Real SHA 256 sum is: `c37c8b93b81e905cdc0ce1aed8b467296748e12991ffbb2ea80892b09dfd2db3`
where the existing one: `3bb1e237b99d785e8303d7df6afe5d6b25bdd16363b81177b6f747f485ca7965`

And why there is `latest` tag an all versions? 
If i took for example: https://github.com/armosec/kubescape/releases/tag/v1.0.127, it is also latest?

**Comment by dwertent** [comment]
Thank you.
Has been update since :)
